# Keep in sync with .editorconfig
newline_style = "LF"
trim_trailing_whitespace = true

max_width = 80

tab_spaces = 2
indent_style = "Spaces"
hard_tabs = false

format_strings = true
wrap_comments = true

imports_granularity = "Crate"
group_imports = "StdExternalCrate"
